# prefix will be prepended to all resource names
variable "prefix" {
  type    = string
  default = "nodejs"
}

# description of the function
variable "description" {
  type    = string
  default = "Sample deploy-from-obs"
}

# FunctionGraph: Function name
variable "function_name" {
  type    = string
  default = "deploy-from-obs"
}

variable "handler_name" {
  type    = string
  default = "src/index.handler"
}

variable "initializer_name" {
  type    = string
  default = "src/index.initializer"
}

# name of zip file to deploy, generated by 'mvn package' command
variable "zip_file_name" {
  type    = string
  default = "../deploy-from-obs.zip"
}

# Resource tag:
variable "tag_app_group" {
  type    = string
  default = "deploy-from-obs"
}
