"use strict";
const { CTSUserInfo } = require("./ctsuserinfo");

/**
 * CTSEvent Class
 * Represents a CTS event for FunctionGraph
 */
class CTSEvent {
  constructor(event) {
    this._event = (event && event.cts) || {};
  }

  /**
   * Timestamp when a trace was generated.
   * The value is the local standard time, for example, 1660927593570.
   * This field is transmitted and stored in the form of a timestamp.
   * It is the total number of milliseconds from 00:00:00, January 1, 1970 to the current time.
   */
  getTime() {
    return this._event.time || 0;
  }

  /**
   * Information of the user who performed the operation that triggered the trace.
   */
  getUser() {
    return new CTSUserInfo(this._event.user);
  }

  /**
   *
   * Request of an operation on resources.
   */
  getRequest() {
    return this._event.request || {};
  }

  /**
   * Response to a user request, that is, the returned information for an operation on resources.
   */
  getResponse() {
    return this._event.response || {};
  }

  /**
   * Type of a cloud service whose traces are to be queried.
   */
  getServiceType() {
    return this._event.service_type || "";
  }

  /**
   * Trace type.
   */
  getEventType() {
    return this._event.event_type || "";
  }

  /**
   * ID of the project to which the trace belongs.
   */
  getProjectId() {
    return this._event.project_id || "";
  }

  /**
   * Type of the resource on which the operation was performed.
   */
  getResourceType() {
    return this._event.resource_type || "";
  }

  /**
   * ID of the account to which the resource belongs.
   * This parameter has a value only when resources are operated across tenants.
   * For example, if tenant A operates resources of tenant B, the value is the
   * account ID of account B.
   * Note: In the cross-tenant scenario, CTS copies an audit log so that both tenants
   * can view the trace on the CTS console.
   */
  getResourceAccountId() {
    return this._event.resource_account_id || "";
  }

  /**
   * Whether a user request is read-only.
   */
  getReadOnly() {
    return this._event.read_only || false;
  }

  /**
   * Name of the tracker that records the trace.
   * When trace_type is set to system, the default value system is used.
   * When trace_type is set to data, the value is the name of the corresponding data tracker.
   */
  getTrackerName() {
    return this._event.tracker_name || "";
  }

  /**
   * Operation ID of the trace.
   */
  getOperationId() {
    return this._event.operation_id || "";
  }

  /**
   * Name of a resource on which the recorded operation was performed.
   */
  getResourceName() {
    return this._event.resource_name || "";
  }

  /**
   * ID of a cloud resource on which the recorded operation was performed.
   */
  getResourceId() {
    return this._event.resource_id || "";
  }

  /**
   * IP address of the tenant who performed the operation that triggered the trace.
   *  The value of this parameter is empty if the operation is triggered by the system.
   */
  getSourceIP() {
    return this._event.source_ip || "";
  }

  /**
   * ID of the account that triggers the trace.
   */
  getDomainId() {
    return this._event.domain_id || "";
  }

  /**
   * Trace name.
   */
  getTraceName() {
    return this._event.trace_name || "";
  }

  /**
   * Trace status. The value can be normal, warning, or incident.
   * normal: The operation succeeded.
   * warning: The operation failed.
   * incident: The operation caused a serious consequence, for example,
   * a node failure or service interruption.
   * @deprecated This parameter is deprecated. Use getTraceRating() instead.
   */
  getTraceStatus() {
    return this._event.trace_status || "";
  }

  /**
   * Trace status. The value can be normal, warning, or incident.
   * normal: The operation succeeded.
   * warning: The operation failed.
   * incident: The operation caused a serious consequence, for example,
   * a node failure or service interruption.
   */
  getTraceRating() {
    return this._event.trace_rating || "";
  }

  /**
   * Trace source. For management traces, the value can be ApiCall,
   * ConsoleAction, or SystemAction. For data traces,
   * the value can be ObsSDK or ObsAPI.
   */
  getTraceType() {
    return this._event.trace_type || "";
  }

  /**
   * Version of the API called in a trace.
   */
  getAPIVersion() {
    return this._event.api_version || "";
  }

  /**
   * Remarks added by other cloud services to a trace.
   */
  getMessage() {
    return this._event.message || "";
  }

  /**
   * Timestamp when a trace was recorded by CTS.
   */
  getRecordTime() {
    return this._event.record_time || "";
  }

  /**
   * Trace ID. The value is the UUID generated by the system.
   */
  getTraceId() {
    return this._event.trace_id || "";
  }

  /**
   * HTTP status code returned by the associated API.
   */
  getCode() {
    return this._event.code || "";
  }

  /**
   * Request ID.
   */
  getRequestId() {
    return this._event.request_id || "";
  }

  /**
   * Additional information required for fault locating after a request error.
   */
  getLocationInfo() {
    return this._event.location_info || {};
  }

  /**
   * Endpoint in the detail page URL of the cloud resource on
   * which a recorded operation was performed.
   */
  getEndpoint() {
    return this._event.endpoint || "";
  }

  /**
   * Detail page URL (excluding the endpoint) of the cloud resource
   * on which a recorded operation was performed.
   */
  getResourceURL() {
    return this._event.resource_url || "";
  }

  /**
   * ID of the enterprise project to which the resource belongs.
   */
  getEnterpriseProjectId() {
    return this._event.enterprise_project_id || "";
  }

  /**
   * ID of the request client agent.
   */
  getUserAgent() {
    return this._event.user_agent || "";
  }

  /**
   * Length of the request message body.
   */
  getContentLength() {
    return this._event.content_length || 0;
  }

  /**
   * Request response time.
   */
  getTotalTime() {
    return this._event.total_time || 0;
  }

  toJSON() {
    return this._event;
  }
}

module.exports = { CTSEvent };
